preload = /home/L/.config/wallpapers/arch_purple.png
preload = /home/L/.config/wallpapers/118016954_p0.png
preload = /home/L/.config/wallpapers/118205969_p0.jpg
preload = /home/L/.config/wallpapers/satellites compressed.png
preload = /home/L/.config/wallpapers/115315413_p0.jpg

wallpaper = , /home/L/.config/wallpapers/115315413_p0.jpg

